"""
Update HTAN typed task data with validated v1.2.0_typed synthetic data.

Copies input_data.tsv and ground_truth.tsv from:
  benchmarking/sim-input/synthetic-data/htan2/v1.2.0_typed/{schema}_{type}/
To:
  curator-benchmarking/tasks/htan_{schema}_{type}/

This updates the 39 HTAN typed tasks with the realistic error patterns generated by Goose.
"""

import shutil
from pathlib import Path

# Paths
REPO_ROOT = Path(__file__).parent.parent.parent
SYNTHETIC_DATA_ROOT = REPO_ROOT / "benchmarking/sim-input/synthetic-data/htan2/v1.2.0_typed"
TASKS_ROOT = REPO_ROOT / "curator-benchmarking/tasks"


def update_task_data(source_dir: Path, task_name: str) -> bool:
    """Update input_data.tsv and ground_truth.tsv for a task."""
    task_dir = TASKS_ROOT / task_name

    if not task_dir.exists():
        print(f"  WARNING: Task directory not found: {task_dir}")
        return False

    # Copy input_data.tsv
    source_input = source_dir / "input_data.tsv"
    if source_input.exists():
        shutil.copy2(source_input, task_dir / "input_data.tsv")
        print(f"  ✓ Updated input_data.tsv")
    else:
        print(f"  WARNING: Source input_data.tsv not found in {source_dir}")
        return False

    # Copy ground_truth.tsv
    source_truth = source_dir / "ground_truth.tsv"
    if source_truth.exists():
        shutil.copy2(source_truth, task_dir / "ground_truth.tsv")
        print(f"  ✓ Updated ground_truth.tsv")
    else:
        print(f"  WARNING: Source ground_truth.tsv not found in {source_dir}")
        return False

    return True


def main():
    """Update all 39 HTAN typed tasks."""
    print("=" * 70)
    print("Updating HTAN Typed Tasks with v1.2.0_typed Synthetic Data")
    print("=" * 70)

    if not SYNTHETIC_DATA_ROOT.exists():
        print(f"ERROR: Synthetic data root not found: {SYNTHETIC_DATA_ROOT}")
        return

    # Get all typed dataset directories
    dataset_dirs = sorted([d for d in SYNTHETIC_DATA_ROOT.iterdir() if d.is_dir()])

    print(f"\nFound {len(dataset_dirs)} typed datasets")
    print(f"Source: {SYNTHETIC_DATA_ROOT}")
    print(f"Target: {TASKS_ROOT}")
    print()

    updated_count = 0
    failed_count = 0

    for dataset_dir in dataset_dirs:
        # Dataset dir name format: {schema}_{type} (e.g., biospecimen_imputation)
        dataset_name = dataset_dir.name
        task_name = f"htan_{dataset_name}"

        print(f"\nUpdating {task_name}...")
        print(f"  Source: {dataset_dir.name}")

        if update_task_data(dataset_dir, task_name):
            updated_count += 1
        else:
            failed_count += 1

    print("\n" + "=" * 70)
    print("Update Complete!")
    print("=" * 70)
    print(f"\n✓ Updated: {updated_count} tasks")
    if failed_count > 0:
        print(f"✗ Failed: {failed_count} tasks")

    print(f"\nNext steps:")
    print(f"  1. Review changes: git status")
    print(f"  2. Test a task: python -m src.cli run htan_demographics_typos --limit 3")
    print(f"  3. Commit changes and create PR")


if __name__ == "__main__":
    main()
